// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function ImportProfile(arg1, arg2) {
  return window['go']['main']['App']['ImportProfile'](arg1, arg2);
}

export function InspectCredentials(arg1) {
  return window['go']['main']['App']['InspectCredentials'](arg1);
}

export function LaunchBrowser(arg1) {
  return window['go']['main']['App']['LaunchBrowser'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SyncCredentials(arg1, arg2) {
  return window['go']['main']['App']['SyncCredentials'](arg1, arg2);
}
