// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProfile(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:boolean):Promise<void>;

export function DetectBrowsers():Promise<Array<main.BrowserItem>>;

export function ImportProfile(arg1:string,arg2:string):Promise<void>;

export function InspectCredentials(arg1:string):Promise<main.CredentialResult>;

export function LaunchBrowser(arg1:string):Promise<void>;

export function ListProfiles():Promise<Array<main.ProfileInfo>>;

export function SelectDirectory():Promise<string>;

export function SyncCredentials(arg1:string,arg2:string):Promise<main.SyncResult>;
